WildcatMicroFund/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using WildcatMicroFund.Data.Context;
using WildcatMicroFund.Data.Models;

namespace WildcatMicroFund.Views
{
    public class ApplicationsController : Controller
    {
        private readonly WildcatMicroFundDatabaseContext _context;

        public ApplicationsController(WildcatMicroFundDatabaseContext context)
        {
            _context = context;
        }

        // GET: Applications
        public async Task<IActionResult> Index()
        {
            /*IEnumerable<ApplicationDetail> applicationDetails = 
                from ApplicationDetail in _context.ApplicationDetails
                where ApplicationDetail.ApplicationID ==  */

            var wildcatMicroFundDatabaseContext = _context.ApplicationDetails.Include(i => i.BusinessStage).Include(i => i.BusinessType).Include(i => i.ConceptStatus);
            return View(await wildcatMicroFundDatabaseContext.ToListAsync());
        }

        // GET: Applications/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ideaApplication = await _context.ApplicationDetails
                .Include(i => i.BusinessStage)
                .Include(i => i.BusinessType)
                .Include(i => i.ConceptStatus)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (ideaApplication == null)
            {
                return NotFound();
            }

            return View(ideaApplication);
        }

        // GET: Applications/Create
        public IActionResult Create()
        {
            ViewData["BusinessStageID"] = new SelectList(_context.BusinessStages, "ID", "BusinessStageDescription");
            ViewData["BusinessTypeID"] = new SelectList(_context.BusinessTypes, "ID", "BusinessTypeDescription");
            ViewData["ConceptStatusID"] = new SelectList(_context.ConceptStatuses, "ID", "ConceptStatusDescription");
            return View();
        }

        // POST: Applications/Create
        // Create a new application and application details.

        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Concept,ConceptStatusID,SalesGenerated,SalesGeneratedInformation,BusinessStageID,BusinessIdeaDescription,HasPrototypeOrIntellectualProperty,PrototypeDescription,BusinessTypeID,MarketOpportunity,EvidenceOfViableOpportunity,CustomerDescription,MarketingAndSales,BusinessCosts,CompetitionDescription,TeamDescription,SpecificRequest")] ApplicationDetail applicationDetail)
        {
            if (ModelState.IsValid)
            {
                // Create the Application
                Application application = new Application();
                application.DateApplied = DateTime.Now;
                var applicationStatus = _context.ApplicationStatuses
                    .Where(a => a.Description == "Applicantion in work").FirstOrDefault<ApplicationStatus>();
                application.ApplicationStatus = applicationStatus;


                // Add Date to applicationDetails
                applicationDetail.DateChanged = DateTime.Now;
                
                // Add the rows to the database.
                _context.Add(application);
                await _context.SaveChangesAsync();
                applicationDetail.Application = application;
                _context.Add(applicationDetail);


                // _context.Applications.Add(application);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            ViewData["BusinessStageID"] = new SelectList(_context.BusinessStages, "ID", "BusinessStageDescription", applicationDetail.BusinessStageID);
            ViewData["BusinessTypeID"] = new SelectList(_context.BusinessTypes, "ID", "BusinessTypeDescription", applicationDetail.BusinessTypeID);
            ViewData["ConceptStatusID"] = new SelectList(_context.ConceptStatuses, "ID", "ConceptStatusDescription", applicationDetail.ConceptStatusID);
            return View(applicationDetail);
        }

        // GET: Applications/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ideaApplication = await _context.ApplicationDetails.FindAsync(id);
            if (ideaApplication == null)
            {
                return NotFound();
            }
            ViewData["BusinessStageID"] = new SelectList(_context.BusinessStages, "ID", "BusinessStageDescription", ideaApplication.BusinessStageID);
            ViewData["BusinessTypeID"] = new SelectList(_context.BusinessTypes, "ID", "BusinessTypeDescription", ideaApplication.BusinessTypeID);
            ViewData["ConceptStatusID"] = new SelectList(_context.ConceptStatuses, "ID", "ConceptStatusDescription", ideaApplication.ConceptStatusID);
            return View(ideaApplication);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        // This will save a new application details to the database with a new date changed so old applications are saved.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, 
            [Bind("Concept,ConceptStatusID,SalesGenerated,SalesGeneratedInformation,BusinessStageID,BusinessIdeaDescription,HasPrototypeOrIntellectualProperty,PrototypeDescription,BusinessTypeID,MarketOpportunity,EvidenceOfViableOpportunity,CustomerDescription,MarketingAndSales,BusinessCosts,CompetitionDescription,TeamDescription,SpecificRequest")] ApplicationDetail applicationDetail)
        {
            /*if (id != applicationDetail.ID)
            {
                return NotFound();
            }*/

            if (ModelState.IsValid)
            {
                try
                {
                    // find the application to connect it to.
                    var oldApplicationDetails = _context.ApplicationDetails
                        .Where(ad => ad.ID == id).FirstOrDefault<ApplicationDetail>();

                    // Connect the new applicationDetail to the existing application.
                    applicationDetail.Application = oldApplicationDetails.Application;
                    applicationDetail.ApplicationID = oldApplicationDetails.ApplicationID;
                    applicationDetail.DateChanged = DateTime.Now;
                    _context.ApplicationDetails.Update(applicationDetail);
                    
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IdeaApplicationExists(applicationDetail.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BusinessStageID"] = new SelectList(_context.BusinessStages, "ID", "BusinessStageDescription", applicationDetail.BusinessStageID);
            ViewData["BusinessTypeID"] = new SelectList(_context.BusinessTypes, "ID", "BusinessTypeDescription", applicationDetail.BusinessTypeID);
            ViewData["ConceptStatusID"] = new SelectList(_context.ConceptStatuses, "ID", "ConceptStatusDescription", applicationDetail.ConceptStatusID);
            return View(applicationDetail);
        }

        // GET: Applications/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ideaApplication = await _context.ApplicationDetails
                .Include(i => i.BusinessStage)
                .Include(i => i.BusinessType)
                .Include(i => i.ConceptStatus)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (ideaApplication == null)
            {
                return NotFound();
            }

            return View(ideaApplication);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {



            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IdeaApplicationExists(int id)
        {
            return _context.ApplicationDetails.Any(e => e.ID == id);
        }
    }
}

WildcatMicroFund/Views/Administrator/AdminReports.cshtml
@{
    ViewData["Title"] = "Reports";
    Layout = "~/Views/Administrator/_layout.cshtml";
}

<p1>Reports</p1>

WildcatMicroFund/Views/Administrator/ApplicationStatus.cshtml
@{
    ViewData["Title"] = "Application Status";
    Layout = "~/Views/Administrator/_layout.cshtml";
}


@model IEnumerable<WildcatMicroFund.Data.Models.Application>
@using System.Linq;


<!DOCTYPE html>

<html>
<head>
    
        <style>
            table {
                font-family: Arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
            }

            td, th {
                border: 1px solid #dddddd;
                text-align: left;
                padding: 10px;
            }

        </style>
   
</head>

<body>
    <h2>Application Status Lookup</h2>

    <table>
        <tr>
            <th>First Name</th>
            <th>Business Name</th>
            <th>Application Status</th>
            <th>Change Status</th>

        </tr>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User.FirstName)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Business.BusinessName)
                </td>

                <td>
                    @Html.DisplayFor(ModelItem => item.ApplicationStatus.Description)
                </td>

                <td>
                    <a asp-action="ChangeStatus" asp-route-id="@item.ID">Change Status</a>
                </td>

            </tr>
            }
        </tbody>
    </table>
</body>
</html>

WildcatMicroFund/Views/Administrator/Assign.cshtml
@{ ViewData["Title"] = "Assign Role";
    Layout = "~/Views/Administrator/_layout.cshtml";
}

@*@model List<WildcatMicroFund.Data.Models.UserRole>*@
@model WildcatMicroFund.Data.Models.UserRole

@using System.Linq


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Assign User Role</title>
</head>
<body>

    <div>
        <h4>UserRole</h4>
        <hr />
        <dl class="row">
            @*            @{var roleList = Model.Select(a => a.Role.RoleDescription);}*@
            <dt class="col-sm-2">
                User Name:
            </dt>
            <dd class="col-sm-10">
                @*              @Html.DisplayNameFor(a => a.User.FirstName)*@
                @Html.DisplayFor(a => a.User.FirstName)
                @*              @Html.DisplayNameFor(a => a.User.LastName)*@
                @Html.DisplayFor(a => a.User.LastName)
            </dd>
            <dt class="col-sm-2">
                User Roles:
            </dt>
            <dd class="col-sm-10">
                @*              @Html.DisplayNameFor(a => a.Role.RoleDescription)*@
                @Html.DisplayFor(a => a.Role.RoleDescription)
            </dd>
        </dl>
        <a asp-action="Users">Back to Users</a>
    </div>
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <select asp-for="Role" class="form-control" asp-items="ViewBag.RoleID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Assign" class="btn btn-primary" />
            </div>
        </form>
    </div>
</body>
</html>

WildcatMicroFund/Views/Administrator/AssignStatus.cshtml
@{
    ViewData["Title"] = "Status";
    Layout = "~/Views/Administrator/_layout.cshtml";
}

@model IEnumerable<WildcatMicroFund.Data.Models.User>

<p>
    Change Status of application here?
    Should this be shared with different dashboards
</p>


<html>
<style>
    table {
        font-family: Arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>
<body>

    <label for="status">Search: </label>
    <select name="status" id="status">
        <option value="Application Complete">Application Complete </option>
    </select>
    <button type="submit">Go</button>
    <br />
    <h2> This is the list of available applications </h2>
    <br />

    <table>

        <tr>
            <th>Application ID</th>
            <th>Name</th>
            <th>Business</th>
            <th>Status</th>
        </tr>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserRoles)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Applications)
                </td>
                <td>
                    <a asp-controller="Administrator" asp-action="Assign">Assign User Role</a>
                </td>
            </tr>
            }
        </tbody>

    </table>

    <label for="applicationID">Application ID</label>
    <input type="text" id="applicationID" name="applicationID" /><br />

    <label for="changeStatus">Change Status</label>
    <select name="changeStatus" id="changeStatus">
        <option value="Application in Review">Application in Review</option>
    </select>
    <br />
    <br />
    
    <button type="submit">Set Status</button>

</body>

</html>

WildcatMicroFund/Views/Administrator/ChangeStatus.cshtml
@{
    ViewData["Title"] = "Application Status";
    Layout = "~/Views/Administrator/_layout.cshtml";
}

@model WildcatMicroFund.Data.Models.Application


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Application Status</title>
</head>
<body>

    <div>
        <h4>Application Status</h4>
        <hr />
        <dl class="row">

            <dt class="col-sm-2">
                Application Status
            </dt>
            <dd class="col-sm-10">

                @Html.DisplayFor(i => i.ApplicationStatus.Description)
            </dd>
        </dl>
    </div>
    <div class="col-md-4">
        <form asp-action="ApplicationStatus">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            
                <div class="form-group">
                    <label asp-for="ApplicationStatusID" class="control-label">Application Status</label>
                    
                <select asp-for="ApplicationStatusID" class="form-control" asp-items="ViewBag.ApplicationStatusID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Change" class="btn btn-primary" />
            </div>
        </form>
    </div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>
</html>

WildcatMicroFund/Views/Administrator/Edit.cshtml
@{
    ViewData["Title"] = "Users";
    Layout = "~/Views/Administrator/_layout.cshtml";
}

@model WildcatMicroFund.Data.Models.User


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

    <h4>User</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ID" />
                <div class="form-group">
                    <label asp-for="Email" class="control-label">Email</label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label">First Name</label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label">Last Name</label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label">Phone Number</label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="GenderID" class="control-label">Gender</label>
                    <select asp-for="GenderID" class="form-control" asp-items="ViewBag.GenderID"></select>
                    <span asp-validation-for="GenderID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EthnicityID" class="control-label">Ethnicity</label>
                    <select asp-for="EthnicityID" class="form-control" asp-items="ViewBag.EthnicityID"></select>
                    <span asp-validation-for="EthnicityID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StreetAddress" class="control-label">Address</label>
                    <input asp-for="StreetAddress" class="form-control" />
                    <span asp-validation-for="StreetAddress" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label">City</label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="State" class="control-label">State</label>
                    <input asp-for="State" class="form-control" />
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Zip" class="control-label">Zip</label>
                    <input asp-for="Zip" class="form-control" />
                    <span asp-validation-for="Zip" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Users">Back to Users</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>
</html>

WildcatMicroFund/Views/Administrator/Index.cshtml
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Administrator/_layout.cshtml";
}

<h1>Welcome, User</h1>
<body>
    <p>Select any option along the top!</p>
</body>

WildcatMicroFund/Views/Administrator/NewApplication.cshtml
@{
    ViewData["Title"] = "New Application";
    Layout = "~/Views/Administrator/_layout.cshtml";
}

<p1>Create a new application here</p1>

WildcatMicroFund/Views/Administrator/Reports.cshtml
@{
    ViewData["Title"] = "Reports";
    Layout = "~/Views/Administrator/_layout.cshtml";
}

<p1>Reports</p1>

WildcatMicroFund/Views/Administrator/UserEdit.cshtml
@{
    ViewData["Title"] = "User Edit";
    Layout = "~/Views/Administrator/_layout.cshtml";
}

<p1>Application Status</p1>

WildcatMicroFund/Views/Administrator/UserLookup.cshtml
@{
    ViewData["Title"] = "User Lookup";
    Layout = "~/Views/Administrator/_layout.cshtml";
}

<p1>User Lookup here</p1>

WildcatMicroFund/Views/Administrator/Users.cshtml
@{
    ViewData["Title"] = "Users";
    Layout = "~/Views/Administrator/_layout.cshtml";
}
@model IEnumerable<WildcatMicroFund.Data.Models.User>
@using System.Linq;

<p>Here is a list of all the users</p>

<html>
<head>
    <style>
        table {
            font-family: Arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>

<body>
    <h2>User Lookup</h2>

    <table>
        <tr>
            <th>First Name</th>
            <th>User Role</th>
            <th>User Email</th>
            <th>Assign</th>
            <th>Edit</th>
        </tr>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @string.Join(", ",  item.UserRoles.Select(a => a.Role.RoleDescription))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <a asp-action="Assign" asp-route-id="@item.ID">Assign</a>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</body>
</html>

WildcatMicroFund/Views/Administrator/_layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WildcatMicroFund</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/WildcatMicrofund_horizontal-01.jpg"
                         style="width:175px;height:50px;">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Administrator" asp-action="Users">Users</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Applications" asp-action="Index">Applications</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Administrator" asp-action="Reports">Reports</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Administrator" asp-action="ApplicationStatus">Application Status</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Administrator" asp-action="Index"><img id="homebutton" src="~/Images/HomeIcon.jpg" /></a>
                            </li>

                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WildcatMicroFund - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>